### ISSUE TITLE
PerformanceElementTiming keeps its Element alive

### ISSUE THREAD

**Issue by foolip** [WICG/element-timing#21]
https://wicg.github.io/element-timing/#sec-performance-element-timing says:

> The element attribute’s getter must run the get an element algorithm with context object’s element and null as inputs.
>
> Note: This means that an element that is no longer descendant of the Document will no longer be returned by element's attribute getter.

The [implementation in Chromium](https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/timing/performance_element_timing.cc?l=66&rcl=580a26a89a1d38a9de1fcbb6d50bf79272c8d507) matches this with one important exception: the Element is held as a weak pointer, and if it's garbage collected the `element` attribute will begin returning null. (This is at odds with the [do not expose garbage collection](https://w3ctag.github.io/design-principles/#js-gc) design principle.)

The spec's [get an element](https://wicg.github.io/element-timing/#get-an-element) algorithm will also cause null to be returned in some cases, but AFAICT implementing it per spec would require holding onto both the element and its original document as strong references.

**Comment by foolip** [comment]
Removing the `element` attribute and requiring developers to use `document.querySelector('[elementtiming=identifier]')` would "fix" the problem. No example in the README or spec uses `entry.element`, so maybe that would be acceptable? It wouldn't work for https://github.com/WICG/largest-contentful-paint/issues/29 where the "elementtiming" attribute isn't required, however.

**Comment by npm1** [comment]
Hmm ideally we'd be able to keep the Element attribute. I'm not entirely sure we expose GC here: if an Element is GCd when it's still attached to the document then can the window still be alive? Otherwise not sure how we expose GC? Note that the entries are not clonable so I think you can only see them from the frame where they were created.

**Comment by domenic** [comment]
You can probably access them from iframe.contentWindow.performance.whateverTheCodeIsToGetEntries().

**Comment by npm1** [comment]
You cannot get these entries from the `performance` object, it needs to come from `PerformanceObserver`. But for now let's assume that the current state does expose GC in some cases. The fixes I see are:

* Change Chrome implementation to use Member instead of WeakMember, keep the spec as is.
* Change the spec to have the stronger check: `shadow-including root is the relevant global object's associated document`, and modify the implementation as such. This was suggested by @yoavweiss, I think this would fix the leak since the document cannot be GCd if it is the Window's associated document?

**Comment by yoavweiss** [comment]
Fixed by #24
