### ISSUE TITLE
Element opt-out from being considered in timing?

### ISSUE THREAD

**Issue by getify** [WICG/element-timing#57]
I am auditing the Lighthouse scores for a PWA I've built, and I'm dismayed to see that my "LCP" is much higher than the rest of my app's metrics. For example, on mobile, my FCP is 1.5s and my TTI is 2.6s, but my LCP is 8.0s. This is really bringing down my score.

The thing is, I'm not painting any new content after those first couple of seconds... except for one extra additional element. I set a timer on page load, and 5-6 seconds later, I pop in a semi-transparent (background-image) image that animates in and shows some touch-centric usage hints (like how to swipe around)... it's literally just an optional usage aide -- it's *not* primary content. It's not even particularly large, not as large as several of the other images that have been displayed in the content.

<img width="250" alt="hint-image" src="https://user-images.githubusercontent.com/150330/112368309-f05db700-8ca8-11eb-94ff-3daec194d211.png">

I'm not positive this element is what's triggering Lighthouse to think my LCP is happening that much later from the rest of my content loading, but it seems likely given the timing coincidentally corresponds pretty close to when that animated hint shows up.

Anyway, here's my question... can I do something like `eventtiming=""` or `eventtiming="false"` or something like that, to opt out a non-primary element like my hint from being considered for these event timing metrics?

**Comment by npm1** [comment]
This sounds a bit more related to LCP but I can reply here anyways... there is no current way to opt something out of being an LCP candidate. LCP is a heuristic that works out of the box, and for developers that want to dig depeer they can use Element Timing on elements whose rendering performance they care about. I would suggest checking the sizes of the images since it seems from the screenshot that it shouldn't be the main content. I would suggest trying a local reproduction to see what's going on. If you find that the image is actually not the largest but is being considered the LCP regardless you can file an issue in https://crbug.com/new
